import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Checkout Pagamento",
  icons: {
    icon: "https://media.licdn.com/dms/image/v2/C4D0BAQH0lo-u5Wpe7g/company-logo_200_200/company-logo_200_200/0/1654550785312/mapmarketplaces_logo?e=2147483647&v=beta&t=uc-BPtacGsO7DjuAtE9pxFPcCuhjCPgGn2MhPkfoDFs",
  },
  description: "Generated by MAP DEVS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
